# Generated by Django 5.0 on 2023-12-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_approval', models.BooleanField(default=False)),
                ('state_approval', models.BooleanField(default=False)),
                ('final_approval', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.institute')),
                ('state_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stateauthority')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_photo', models.ImageField(upload_to='user_detail/')),
                ('domicile_certificate', models.ImageField(upload_to='user_detail/')),
                ('income_certficate', models.ImageField(upload_to='user_detail/')),
                ('caste_certificate', models.ImageField(upload_to='user_detail/')),
                ('aadhar_card', models.ImageField(upload_to='user_detail/')),
                ('bonafide', models.ImageField(upload_to='user_detail/')),
                ('fee_receipt', models.ImageField(upload_to='user_detail/')),
                ('passbook', models.ImageField(upload_to='user_detail/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_docs', to='users.student')),
            ],
        ),
    ]
