# Generated by Django 5.0 on 2023-12-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username_alter_student_domicile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='domicile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stateauthority'),
        ),
    ]
