# Generated by Django 5.0 on 2023-12-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_domicile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='domicile',
        ),
        migrations.AddField(
            model_name='student',
            name='domicile_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stateauthority'),
        ),
    ]
